image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.1"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

env:
  password: MYPASSWORD

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: local.metrics-app.io
      paths:
        - path: /counter
          pathType: Prefix



serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

